// <auto-generated />
namespace TicketsUNO27.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Createprojectstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Createprojectstable));
        
        string IMigrationMetadata.Id
        {
            get { return "202210312258456_Create projects table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
